services:
  omniboard-app:
    image: omniboard/omniboard-app
    restart: always
    ports:
      - 80:80
    environment:
      API_URL: http://localhost:8080
      CONFIG_VARS: API_URL

  omniboard-api:
    image: omniboard/omniboard-api
    restart: always
    ports:
      - 8080:8080
    environment:
      OB_ORG_NAME: 'Awesome Inc.'
      OB_ORG_ADMIN_EMAIL: admin@awesome.com
      OB_ORG_ADMIN_PASSWORD_FILE: /run/secrets/api-admin-password
      ENV: docker
      TZ: UTC
      PORT: 8080
      OB_JWT_SECRET: something_unique_doesnt_really_matter_what
      OB_DB_HOST: omniboard-db
      OB_DB_DATABASE: omniboard
      OB_DB_USERNAME_FILE: /run/secrets/db-user
      OB_DB_PASSWORD_FILE: /run/secrets/db-user-password
    secrets:
      - db-user
      - db-user-password
      - db-root-password
      - api-admin-password

  omniboard-db:
    platform: linux/x86_64 # M1 workaround
    image: mysql:5.7.37
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: omniboard
      MYSQL_USER_FILE: /run/secrets/db-user
      MYSQL_PASSWORD_FILE: /run/secrets/db-user-password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-root-password
    volumes:
      - omniboard-db-data:/var/lib/mysql
    secrets:
      - db-user
      - db-user-password
      - db-root-password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    environment:
      ADMINER_DEFAULT_SERVER: omniboard-db
      ADMINER_DESIGN: dracula

volumes:
  omniboard-db-data:

secrets:
  db-user:
    file: ./db-user
  db-user-password:
    file: ./db-user-password
  db-root-password:
    file: ./db-root-password
  api-admin-password:
    file: ./api-admin-password
